### ISSUE TITLE
How to use it from node.js 4 stable?

### ISSUE THREAD

**Issue by periloso** [c58/marsdb#3]
I was trying to use marsdb as a replacement of linvodb3 because I would prefer to use promises, however I think I'm giving up.

Here's what happens:

```
let Mongo = require('marsdb');
let Doc = new Mongo(modelName, schema, options);
```

gives me the following error:
```
TypeError: Mongo is not a function
```

The let Doc is taken from the linvodb3 library, and since there isn't really an example on how to use it on node, I think I'm stuck :(

Thanks in advance for the help! :)

**Comment by c58** [comment]
Hi, @periloso 

First of all, MarsDB is not a drop-in replacement of LinvoDB and i'v removed some features, like schemas. So, `let Doc = new Mongo(modelName, schema, options);` really accepts only first argument.

Secondary, a working example without using ES2015 imports is
```javascript
let Collection = require("marsdb").Collection;
let TestColl = new Collection('testColl');
TestColl.insert({a: 1}).then((id) => {
    console.log(id);
});
```

Hope it helps!

**Comment by periloso** [comment]
Oh, that's so cool.. thanks! ^_^
You can close this issue then, in case of bugs or anything else I'll write another one :)
Thanks again! :+1:
