### ISSUE TITLE
[doc] curly single quotes in readme

### ISSUE THREAD

**Issue by BrainCrumbz** [c58/marsdb#6]
Hello all

It seems in https://github.com/c58/marsdb/blob/master/README.md there are several cases of "curly" quotes (so to say):

```
const posts = new Collection(‘posts’);
```

Probably those should be turned into regular single quotes: 

```
const posts = new Collection('posts');
```

just in case one tries copy-pasting code bits.

HTH

**Comment by c58** [comment]
Thanks, @BrainCrumbz ! Fixed.
